apiVersion: v1
data:
  prometheus-custom-metrics.yaml: "kind: Namespace\napiVersion: v1\nmetadata:\n  name:
    custom-metrics\n  labels:\n    name: custom-metrics\n---\n# Source: prometheus_custom_metrics_helm_chart/templates/custom-metrics-apiserver-service-account.yaml\nkind:
    ServiceAccount\napiVersion: v1\nmetadata:\n  name: custom-metrics-apiserver\n
    \ namespace: custom-metrics\n---\n# Source: prometheus_custom_metrics_helm_chart/templates/custom-metrics-config-map.yaml\napiVersion:
    v1\nkind: ConfigMap\nmetadata:\n  name: adapter-config\n  namespace: custom-metrics\ndata:\n
    \ config.yaml: |\n    rules:\n    - seriesQuery: '{__name__=~\"^container_.*\",container_name!=\"POD\",namespace!=\"\",pod_name!=\"\"}'\n
    \     seriesFilters: []\n      resources:\n        overrides:\n          namespace:\n
    \           resource: namespace\n          pod_name:\n            resource: pod\n
    \     name:\n        matches: ^container_(.*)_seconds_total$\n        as: \"\"\n
    \     metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container_name!=\"POD\"}[1m]))
    by (<<.GroupBy>>)\n    - seriesQuery: '{__name__=~\"^container_.*\",container_name!=\"POD\",namespace!=\"\",pod_name!=\"\"}'\n
    \     seriesFilters:\n      - isNot: ^container_.*_seconds_total$\n      resources:\n
    \       overrides:\n          namespace:\n            resource: namespace\n          pod_name:\n
    \           resource: pod\n      name:\n        matches: ^container_(.*)_total$\n
    \       as: \"\"\n      metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container_name!=\"POD\"}[1m]))
    by (<<.GroupBy>>)\n    - seriesQuery: '{__name__=~\"^container_.*\",container_name!=\"POD\",namespace!=\"\",pod_name!=\"\"}'\n
    \     seriesFilters:\n      - isNot: ^container_.*_total$\n      resources:\n
    \       overrides:\n          namespace:\n            resource: namespace\n          pod_name:\n
    \           resource: pod\n      name:\n        matches: ^container_(.*)$\n        as:
    \"\"\n      metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>,container_name!=\"POD\"})
    by (<<.GroupBy>>)\n    - seriesQuery: '{namespace!=\"\",__name__!~\"^container_.*\"}'\n
    \     seriesFilters:\n      - isNot: .*_total$\n      resources:\n        template:
    <<.Resource>>\n      name:\n        matches: \"\"\n        as: \"\"\n      metricsQuery:
    sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)\n    - seriesQuery: '{namespace!=\"\",__name__!~\"^container_.*\"}'\n
    \     seriesFilters:\n      - isNot: .*_seconds_total\n      resources:\n        template:
    <<.Resource>>\n      name:\n        matches: ^(.*)_total$\n        as: \"\"\n
    \     metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)\n
    \   - seriesQuery: '{__name__=~\"^node_.*\"}'\n      resources:\n        overrides:\n
    \         instance:\n            resource: node\n      name:\n        matches:
    ^node_(.*)\n      metricsQuery: <<.Series>>\n    - seriesQuery: '{namespace!=\"\",__name__!~\"^container_.*\"}'\n
    \     seriesFilters: []\n      resources:\n        template: <<.Resource>>\n      name:\n
    \       matches: ^(.*)_seconds_total$\n        as: \"\"\n      metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}[1m])
    by (<<.GroupBy>>)\n---\n# Source: prometheus_custom_metrics_helm_chart/templates/custom-metrics-cluster-role.yaml\napiVersion:
    rbac.authorization.k8s.io/v1\nkind: ClusterRole\nmetadata:\n  name: custom-metrics-server-resources\nrules:\n-
    apiGroups:\n  - \"\"\n  resources: [\"*\"]\n  verbs: [\"*\"]\n---\n# Source: prometheus_custom_metrics_helm_chart/templates/custom-metrics-resource-reader-cluster-role.yaml\napiVersion:
    rbac.authorization.k8s.io/v1\nkind: ClusterRole\nmetadata:\n  name: custom-metrics-resource-reader\nrules:\n-
    apiGroups:\n  - \"\"\n  resources:\n  - namespaces\n  - pods\n  - services\n  -
    nodes\n  verbs:\n  - get\n  - list\n  - watch\n---\n# Source: prometheus_custom_metrics_helm_chart/templates/custom-metrics-apiserver-auth-delegator-cluster-role-binding.yaml\napiVersion:
    rbac.authorization.k8s.io/v1\nkind: ClusterRoleBinding\nmetadata:\n  name: custom-metrics:system:auth-delegator\nroleRef:\n
    \ apiGroup: rbac.authorization.k8s.io\n  kind: ClusterRole\n  name: system:auth-delegator\nsubjects:\n-
    kind: ServiceAccount\n  name: custom-metrics-apiserver\n  namespace: custom-metrics\n---\n#
    Source: prometheus_custom_metrics_helm_chart/templates/custom-metrics-apiserver-resource-reader-cluster-role-binding.yaml\napiVersion:
    rbac.authorization.k8s.io/v1\nkind: ClusterRoleBinding\nmetadata:\n  name: custom-metrics-resource-reader\nroleRef:\n
    \ apiGroup: rbac.authorization.k8s.io\n  kind: ClusterRole\n  name: custom-metrics-resource-reader\nsubjects:\n-
    kind: ServiceAccount\n  name: custom-metrics-apiserver\n  namespace: custom-metrics\n---\n#
    Source: prometheus_custom_metrics_helm_chart/templates/custom-metrics-apiserver-auth-reader-role-binding.yaml\napiVersion:
    rbac.authorization.k8s.io/v1\nkind: RoleBinding\nmetadata:\n  name: custom-metrics-auth-reader
    \n  namespace: kube-system\nroleRef:\n  apiGroup: rbac.authorization.k8s.io\n
    \ kind: Role\n  name: extension-apiserver-authentication-reader\nsubjects:\n-
    kind: ServiceAccount\n  name: custom-metrics-apiserver\n  namespace: custom-metrics\n---\n#
    Source: prometheus_custom_metrics_helm_chart/templates/custom-metrics-apiserver-service.yaml\napiVersion:
    v1\nkind: Service\nmetadata:\n  name: custom-metrics-apiserver\n  namespace: custom-metrics\nspec:\n
    \ ports:\n  - port: 443\n    targetPort: 6443\n  selector:\n    app: custom-metrics-apiserver\n---\n#
    Source: prometheus_custom_metrics_helm_chart/templates/custom-metrics-apiserver-deployment.yaml\napiVersion:
    apps/v1\nkind: Deployment\nmetadata:\n  labels:\n    app: custom-metrics-apiserver\n
    \ name: custom-metrics-apiserver\n  namespace: custom-metrics\nspec:\n  replicas:
    1\n  selector:\n    matchLabels:\n      app: custom-metrics-apiserver\n  template:\n
    \   metadata:\n      labels:\n        app: custom-metrics-apiserver\n      name:
    custom-metrics-apiserver\n    spec:\n      serviceAccountName: custom-metrics-apiserver\n
    \     containers:\n      - name: custom-metrics-apiserver\n        image: directxman12/k8s-prometheus-adapter-amd64\n
    \       args:\n        - --secure-port=6443\n        - --tls-cert-file=/var/run/serving-cert/tls.crt\n
    \       - --tls-private-key-file=/var/run/serving-cert/tls.key\n        - --logtostderr=true\n
    \       - --prometheus-url=http://prom-service.monitoring.svc:9090/\n        -
    --metrics-relist-interval=1m\n        - --v=10\n        - --config=/etc/adapter/config.yaml\n
    \       ports:\n        - containerPort: 6443\n        volumeMounts:\n        -
    mountPath: /var/run/serving-cert\n          name: volume-serving-cert\n          readOnly:
    true\n        - mountPath: /etc/adapter/\n          name: config\n          readOnly:
    true\n        - mountPath: /tmp\n          name: tmp-vol\n      volumes:\n      -
    name: volume-serving-cert\n        secret:\n          secretName: cm-adapter-serving-certs\n
    \     - name: config\n        configMap:\n          name: adapter-config\n      -
    name: tmp-vol\n        emptyDir: {}\n---\n# Source: prometheus_custom_metrics_helm_chart/templates/custom-metrics-apiservice.yaml\napiVersion:
    apiregistration.k8s.io/v1\nkind: APIService\nmetadata:\n  name: v1beta1.custom.metrics.k8s.io\nspec:\n
    \ service:\n    name: custom-metrics-apiserver\n    namespace: custom-metrics\n
    \ group: custom.metrics.k8s.io\n  version: v1beta1\n  insecureSkipTLSVerify: true\n
    \ groupPriorityMinimum: 100\n  versionPriority: 100\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: custom-metrics-configmap
