apiVersion: v1
data:
  tas.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: telemetry-aware-scheduling
      namespace: default
      labels:
        app: tas
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: tas
      template:
        metadata:
          labels:
            app: tas
        spec:
          serviceAccountName: telemetry-aware-scheduling-service-account
          containers:
            - name: tasext
              command:
                - /extender
                - --syncPeriod=2s
                - --cert=/tas/cert/tls.crt
                - --key=/tas/cert/tls.key
                - --cacert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                - --v=2
              image: intel/telemetry-aware-scheduling
              imagePullPolicy: IfNotPresent
              securityContext:
                capabilities:
                  drop:
                    - all
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 10001
              volumeMounts:
                - name: certs
                  mountPath: /tas/cert
              resources:
                limits:
                  memory: "500Mi"
                  cpu: "500m"
                requests:
                  memory: "100Mi"
                  cpu: "100m"
          volumes:
            - name: certs
              secret:
                secretName: extender-secret
          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: Exists
    ---
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: taspolicies.telemetry.intel.com
    spec:
      group: telemetry.intel.com
      names:
        kind: TASPolicy
        listKind: TASPolicyList
        plural: taspolicies
        singular: taspolicy
      scope: Namespaced
      versions:
        - name: v1alpha1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              properties:
                apiVersion:
                  description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest'
                  type: string
                kind:
                  description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client'
                  type: string
                metadata:
                  type: object
                spec:
                  properties:
                    strategies:
                      additionalProperties:
                        properties:
                          policyName:
                            type: string
                          logicalOperator:
                            type: string
                            enum: ["allOf", "anyOf"]
                          rules:
                            items:
                              description: Set rules parameters per strategy
                              properties:
                                metricname:
                                  type: string
                                operator:
                                  type: string
                                  enum: ["Equals", "LessThan", "GreaterThan"]
                                target:
                                  format: int64
                                  type: integer
                                labels:
                                  type: array
                                  items:
                                    type: string
                              required:
                                - metricname
                                - operator
                              type: object
                            type: array
                        required:
                          - rules
                        type: object
                      type: object
                  required:
                    - strategies
                  type: object
                status:
                  properties:
                    compliance:
                      type: string
                    message:
                      type: string
                  type: object
          subresources:
            status: {}
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: handle-policies
    subjects:
      - kind: ServiceAccount
        name: telemetry-aware-scheduling-service-account
        namespace: default
    roleRef:
      kind: ClusterRole
      name: policy-handler
      apiGroup: rbac.authorization.k8s.io
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: policy-handler
    rules:
      - apiGroups: ["telemetry.intel.com"]
        resources: ["taspolicies"]
        verbs: ["get", "watch", "list", "delete", "update"]
      - apiGroups: ["custom.metrics.k8s.io"]
        resources: ["*"]
        verbs: ["get"]
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list", "watch", "update"]
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "list", "patch"]
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: telemetry-aware-scheduling-service-account
      namespace: default
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: tas-configmap
