apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ecoqube-mgmt
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: ecoqube-mgmt-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
    kind: OpenStackCluster
    name: ecoqube-mgmt
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackCluster
metadata:
  name: ecoqube-mgmt
  namespace: default
spec:
  cloudName: openstack
  dnsNameservers:
  - 8.8.8.8
  externalNetworkId: 59ba0d05-14c4-4010-94a7-d85ccf6f532c
  identityRef:
    kind: Secret
    name: ecoqube-mgmt-cloud-config
  managedSecurityGroups: true
  nodeCidr: 10.6.0.0/24
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: ecoqube-mgmt-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        extraVolumes:
        - hostPath: /etc/kubernetes/cloud.conf
          mountPath: /etc/kubernetes/cloud.conf
          name: cloud
          readOnly: true
      controllerManager:
        extraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        extraVolumes:
        - hostPath: /etc/kubernetes/cloud.conf
          mountPath: /etc/kubernetes/cloud.conf
          name: cloud
          readOnly: true
        - hostPath: /etc/certs/cacert
          mountPath: /etc/certs/cacert
          name: cacerts
          readOnly: true
      imageRepository: registry.k8s.io
    files:
    - content: W0dsb2JhbF0KYXV0aC11cmw9aHR0cDovLzY0LjIyNy42LjEwMi9pZGVudGl0eQp1c2VybmFtZT0iYWRtaW4iCnBhc3N3b3JkPSJzdGFjayIKdGVuYW50LWlkPSI2NTMxOWI2ZDE3NzM0ZjIwOGU2MjU0NDVjMmMzNzdhMSIKdGVuYW50LW5hbWU9ImFkbWluIgpkb21haW4tbmFtZT0iRGVmYXVsdCIKcmVnaW9uPSJSZWdpb25PbmUiCg==
      encoding: base64
      owner: root
      path: /etc/kubernetes/cloud.conf
      permissions: "0600"
    - content: Cg==
      encoding: base64
      owner: root
      path: /etc/certs/cacert
      permissions: "0600"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        name: '{{ local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
        name: '{{ local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
      kind: OpenStackMachineTemplate
      name: ecoqube-mgmt-control-plane
  replicas: 1
  version: v1.25.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  name: ecoqube-mgmt-control-plane
  namespace: default
spec:
  template:
    spec:
      cloudName: openstack
      flavor: ds4G
      identityRef:
        kind: Secret
        name: ecoqube-mgmt-cloud-config
      image: ubuntu-2004-kube-v1.25.0
      sshKeyName: admin
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: ecoqube-mgmt-md-0
  namespace: default
spec:
  clusterName: ecoqube-mgmt
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: ecoqube-mgmt-md-0
      clusterName: ecoqube-mgmt
      failureDomain: nova
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
        kind: OpenStackMachineTemplate
        name: ecoqube-mgmt-md-0
      version: v1.25.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  name: ecoqube-mgmt-md-0
  namespace: default
spec:
  template:
    spec:
      cloudName: openstack
      flavor: ds4G
      identityRef:
        kind: Secret
        name: ecoqube-mgmt-cloud-config
      image: ubuntu-2004-kube-v1.25.0
      sshKeyName: admin
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: ecoqube-mgmt-md-0
  namespace: default
spec:
  template:
    spec:
      files:
      - content: W0dsb2JhbF0KYXV0aC11cmw9aHR0cDovLzY0LjIyNy42LjEwMi9pZGVudGl0eQp1c2VybmFtZT0iYWRtaW4iCnBhc3N3b3JkPSJzdGFjayIKdGVuYW50LWlkPSI2NTMxOWI2ZDE3NzM0ZjIwOGU2MjU0NDVjMmMzNzdhMSIKdGVuYW50LW5hbWU9ImFkbWluIgpkb21haW4tbmFtZT0iRGVmYXVsdCIKcmVnaW9uPSJSZWdpb25PbmUiCg==
        encoding: base64
        owner: root
        path: /etc/kubernetes/cloud.conf
        permissions: "0600"
      - content: Cg==
        encoding: base64
        owner: root
        path: /etc/certs/cacert
        permissions: "0600"
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-config: /etc/kubernetes/cloud.conf
            cloud-provider: openstack
          name: '{{ local_hostname }}'
---
apiVersion: v1
data:
  cacert: Cg==
  clouds.yaml: Y2xvdWRzOgogIG9wZW5zdGFjazoKICAgIGF1dGg6CiAgICAgIGF1dGhfdXJsOiBodHRwOi8vNjQuMjI3LjYuMTAyL2lkZW50aXR5CiAgICAgIHVzZXJuYW1lOiAiYWRtaW4iCiAgICAgIHBhc3N3b3JkOiBzdGFjawogICAgICBwcm9qZWN0X2lkOiA2NTMxOWI2ZDE3NzM0ZjIwOGU2MjU0NDVjMmMzNzdhMQogICAgICBwcm9qZWN0X25hbWU6ICJhZG1pbiIKICAgICAgdXNlcl9kb21haW5fbmFtZTogIkRlZmF1bHQiCiAgICByZWdpb25fbmFtZTogIlJlZ2lvbk9uZSIKICAgIGludGVyZmFjZTogInB1YmxpYyIKICAgIGlkZW50aXR5X2FwaV92ZXJzaW9uOiAzCg==
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: ecoqube-mgmt-cloud-config
  namespace: default
