---
apiVersion: v1
kind: Service
metadata:
  name: tas-service
  namespace: default
spec:
  selector:
    app: tas
  type: ClusterIP
  ports:
    - port: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-aware-scheduling
  namespace: default 
  labels:
    app: tas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tas
  template:
    metadata:
      labels:
        app: tas
    spec:
      serviceAccountName: telemetry-aware-scheduling-service-account
      containers:
      - name: tasext
        command:
        - /extender
        - --syncPeriod=2s
        - --cert=/tas/cert/tls.crt
        - --key=/tas/cert/tls.key
        - --cacert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --v=2
        image: intel/telemetry-aware-scheduling
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
        volumeMounts:
        - name: certs
          mountPath: /tas/cert
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "100m"
      volumes:
      - name: certs
        secret:
          secretName: extender-secret
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: taspolicies.telemetry.intel.com
  namespace: default
spec:
  group: telemetry.intel.com
  names:
    kind: TASPolicy
    listKind: TASPolicyList
    plural: taspolicies
    singular: taspolicy
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
           apiVersion:
             description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest'
             type: string
           kind:
             description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client'
             type: string
           metadata:
             type: object
           spec:
             properties:
               strategies:
                 additionalProperties:
                   properties:
                     policyName:
                       type: string
                     logicalOperator:
                       type: string
                       enum: ["allOf", "anyOf"]
                     rules:
                       items:
                         description: Set rules parameters per strategy
                         properties:
                           metricname:
                             type: string
                           operator:
                             type: string
                             enum: ["Equals","LessThan","GreaterThan"]
                           target:
                             format: float
                             type: number
                           labels:
                             type: array
                             items:
                               type: string
                         required:
                           - metricname
                           - operator
                         type: object
                       type: array
                   required:
                     - rules
                   type: object
                 type: object
             required:
               - strategies
             type: object
           status:
             properties:
               compliance:
                 type: string
               message:
                 type: string
             type: object
      subresources:
        status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policy-handler
  namespace: default
rules:
- apiGroups: ["telemetry.intel.com"]
  resources: ["taspolicies"]
  verbs: ["get", "watch", "list", "delete", "update"]
- apiGroups: ["custom.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch","update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: handle-policies
  namespace: default
subjects:
  - kind: ServiceAccount
    name: telemetry-aware-scheduling-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: policy-handler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telemetry-aware-scheduling-service-account
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-extender-policy
  namespace: kube-system
data:
  policy.cfg: |
    {
        "kind" : "Policy",
        "apiVersion" : "v1",
        "extenders" : [
            {
              "urlPrefix": "https://tas-service.default.svc.cluster.local:9001",             
              "apiVersion": "v1",
              "prioritizeVerb": "scheduler/prioritize",
              "filterVerb": "scheduler/filter",
              "weight": 1,
              "enableHttps": true,
              "managedResources": [
                   {
                     "name": "telemetry/scheduling",
                     "ignoredByScheduler": true
                   }
              ],
              "ignorable": true,
              "tlsConfig": {
                     "insecure": false,
                     "certFile": "/host/certs/client.crt",
                     "keyFile" : "/host/certs/client.key"
              }
            }
           ]
    }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmapgetter
rules:
- apiGroups: [""]
  resources: ["list, configmaps, watch"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduler-config-map
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmapgetter
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-scheduler
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNsakNDQVg0Q0NRRDZkSC9pQ0ZYYzZUQU5CZ2txaGtpRzl3MEJBUXNGQURBTk1Rc3dDUVlEVlFRRERBSmoKWVRBZUZ3MHlNakEyTURreE1qUTJNakJhRncweU16QTJNRGt4TWpRMk1qQmFNQTB4Q3pBSkJnTlZCQU1NQW1OaApNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZLTHZ4R1hQVkNndFlFckJ4dHp1Cmk5M2JLTURDa25nRFVLMUpwRkRKb1FuRlFnV3REZGU3Q0ZmaXVXT3d0SmR5eWN4dVZXRlJBMEducGhaRUc3S0gKdmVwcnh6dWtjVEhUNHA5bXVUM2QzTTlKY1dQbUdueHd0NXU0Qkt1d3pySk1CbDk1L2g4NnBLL1ZDRDh0U1BHUAovaitBUUF2YzBzWFJYZEc2czJFN05KV0dIRElQVFpEQ01JVTVTMmhKRTIzUlQ5V2F6dVZ4aVJTQThRLzZMNml0CmRDdDZ2QUxqcUhCOTliRUFmQmlsMDFsb1UvYjVuZDVLZTJ6cXo0b2h1NW9pUFZlZjVUck9RT0p4RUZCb1llK08KZEFJT3U1YmdtV2VTWnJVeTRqbldaeWU2TUtacHVIeDhPZzFPTSthUTFwT3JTZUxOcS9HNVdPR0hWUlNKVlBpbApkUUlEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjY1U29PZ3ZTVml0L1RpSFdSMUF6Y25BYklpV1hiCnl1dGxuQmh5UjdzaUwvZzEvUThUSnZVRngrbEtja1ROMGg1R3lzRHZjVkVhM2VVdWQvUUd6eGVnTEVlL1J4aEkKY3NPNGlQMDFINGl0UlVWRjB6bEZXMFdoLy80aXpEMmJjSG5HaUNnaXFZcXlzZEFvMnFBQUdid09IS0EraGtWcgo4TEM0ZW5EMS84OGFONFJiaG9XS0xMMUJEUXpvZXZMaGRDRlB4a3Rtdm5PY3F5Zm01L3BaNTFMYk81cDBWOVhtCjVrekdzaUg4Q1I2Vlc0bFhiUFZjN2tRTCs1OXJGYlV3Wml5U3VVRS9ITjdCWDNsbmtVeVM5cHNWQkZwU3dFdVcKd3RsQ2dLbzVmMW5OR3RjdU1ZUG8vaytxRXRLMHhqTS9NUTRtT3dLQ0VSc1JETEhwMFlSSDJkSlMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV3QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktvd2dnU21BZ0VBQW9JQkFRQzhvdS9FWmM5VUtDMWcKU3NIRzNPNkwzZHNvd01LU2VBTlFyVW1rVU1taENjVkNCYTBOMTdzSVYrSzVZN0MwbDNMSnpHNVZZVkVEUWFlbQpGa1Fic29lOTZtdkhPNlJ4TWRQaW4yYTVQZDNjejBseFkrWWFmSEMzbTdnRXE3RE9za3dHWDNuK0h6cWtyOVVJClB5MUk4WS8rUDRCQUM5elN4ZEZkMGJxellUczBsWVljTWc5TmtNSXdoVGxMYUVrVGJkRlAxWnJPNVhHSkZJRHgKRC9vdnFLMTBLM3E4QXVPb2NIMzFzUUI4R0tYVFdXaFQ5dm1kM2twN2JPclBpaUc3bWlJOVY1L2xPczVBNG5FUQpVR2hoNzQ1MEFnNjdsdUNaWjVKbXRUTGlPZFpuSjdvd3BtbTRmSHc2RFU0ejVwRFdrNnRKNHMycjhibFk0WWRWCkZJbFUrS1YxQWdNQkFBRUNnZ0VCQUo5NUxEU2dVYWYzRTIxOXBkYW1QckZXRFFxbDg1aDZCMnQwSkhiYXFhc1EKSklpTlhlRC9DYXFqQ2hUcTk1K2xEYkVXdUF4TWFuM1RTcFU1NjdoeXRSbFVqbXR2dTdUS2lEUGx5S1ZBYlVsWQpvT0ZRc0Y2aDUzVUNHNDh2U3hsaldLeG1tUzdDWGdTT2RnNHp3dWdRK0VmY2pXTVg1RWI0WCtqdC91WFpoSUVOCmwzemVWQ0kyZDBEbkRUa2swbG0va0EwUmthOWxxMWVLL3VNN1hkQjdhYUhKWENISG8va1JaSmk1YXE0WWtmQ0IKWk5uYUZhUmgxbUszK2xaMEJxcER0aXlDYWNHazBQekphTXN3QU92NVZDTjhoY1NSbTJZVE1TY3gzcmpBQW9uNQorVnpjUGF0b000ZVRzRkVRYjZoeTB4L2cwbVJjdmQ3czBpRUZRREp5QVVFQ2dZRUE2ZFI4MTV4ZzBjVm1yNE91CkZPcEZmMTliRkZsMWlLSFZmTU9aN0o5R3MrVSt6NzMwdTN3alkrazd3T1pIdGZqMVhGL1I3UEpUdk5GdHVyOXkKYzBoWDhDdnJwWjZUM1ViS0grdzVsNk9MZDVhM2xCbVhCek9tT0crTDI5YmJJKysxNy9PeU5RaDFFTE43WVVzUApONHlseWlaaGF1VHpKVG90QjIvQk1SZHZNQ1VDZ1lFQXpvV0RTSmRzMGxQdysrRGhtdk50Qk5mU0ZkTU9lQU9FCmYydHh1NHFMd3lhV3FYUC84Z0lOMXRDZUdMY0x1VUcwUWQ2U1lmTHF0UjdvZ0M5eUdHTmhkeG9zeW5DQWpSVkYKWkYrYU5XdWMrTmRUME9FSkU1Z3I4MDgvTzREVVZaTmZpR0h3Ty8xYW9HMVNqak1BY0x2ZFN6TVRxbXJyc3JSbwpJcysrK0RDOHR4RUNnWUVBeDQyYUJYL2xlT0NZbzgwak1hSkZNVkMxc0FZd3NpdzZ2OEZHaVpQY2lRWnB0bTBNCmdUeU9EMlFxcEpOaU84QjkxUm5KVkFmeXdyK1FmOEdHOFMrYUxOT3V4YWN4MWJQbUo1dzRBbHVHV01iOVlKeisKTVIwNURBeldOUVdGKzRORnA4UTRIOTVaMmFqeThMTllCelkyL3ZBR1QyMll1L3FNRno2ZWgwRFNtU2tDZ1lFQQp1SzFoMmM4M1M5b3VmRDc3MytGZ2t0MGdDODRoZVNiRUhHR0xZY2FoOXBBU1dGUFlBNlRjbFVVV3EwazhuWnhvCndpSnpTazI4bnR5VjB0TWF0ejVma084Q01NRnI0ejJyUVBmUTRZWnE1NGMrZDJKVkNJV2lmOEJVN2pQbExPVk4KbjVyZEJmZ29TNStYSEh2MUg5cVBLRWp6aEFoNjN1SSs0U3BmUG5mdXVkRUNnWUVBblRoYTFRakpoMHM1dkJ2cQp5UVgwWThvbXFkR1QxZldLTncwQTR2MUQ2T2taYk5XRkUzRVVLRUNCUzhEaUc3Q3d6L3NHT20rc2szQU9HVURZCkE4MTd0RFZ3a2VoNEhoRFB5a1dRRVpINXBNUmNWUm5aaU1wUktmUjhGQW42U3NTdzRvWCs5Vkl5RmxBaHFPYSsKeEk2ZWJ3N2NmR01XYTRIYWZLLzluVTgxempvPQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: extender-secret
  namespace: default
type: kubernetes.io/tls