apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "ecoqube-dev"
  namespace: default
  labels:
    cni: calico
    scheduler: tas
spec:
  clusterNetwork:
    services:
      cidrBlocks: ['10.128.0.0/12']
    pods:
      cidrBlocks: ['192.168.0.0/16']
    serviceDomain: 'cluster.local'
  topology:
    class: "ecoqube-tas"
    version: "v1.26.3"
    controlPlane:
      replicas: 1
    variables:
      - name: podSecurityStandard
        value:
          audit: restricted
          enabled: true
          enforce: baseline
          warn: restricted
    workers:
      machineDeployments:
        - class: "default-worker"
          name: "default-worker-topo"
          replicas: 3